### PR TITLE
#1 COLOR_DIR global variable is undefined for some reason

### PR DESCRIPTION
**Pull request by achengli**
I did some modifications in the structure of the code making _color.lua_ return a table instead of a function. That allows to be compatible with the past programming style that the project has before.

_rockspec-1.1-1_ was updated too. I have modified the modules written in _build_ section to fit with the color directory that is where I located all the **Lua** code in this project.

Finally I removed the definition of **COLOR_DIR** because this constant is redundant for the project; you have access to the source files of this project without needing of the global path.

### CODE REVIEW

**Comment by andOrlando** [comment]
I'm pretty sure I added the OLOR_DIR constant because I didn't have access to all the source files. I believe when you don't install it through luarocks, awesomeWM won't know where to look for the files.

Have you tested this with/without luarocks and on awesomeWM?

**Comment by andOrlando** [comment]
I'm pretty sure I added the OLOR_DIR constant because I didn't have access to all the source files. I believe when you don't install it through luarocks, awesomeWM won't know where to look for the files.

Have you tested this without luarocks and on awesomeWM?

Thanks for the luarocks fix but I just wanna be sure it doesn't break compatibility

**Comment by achengli** [comment]
Oh right, I didn't try it out with awesomeWM, I did it only with luarocks because I need it for my neovim  theme configurations.

I'm going to redo the changes to avoid breaking compatibility with awesomeWM.

**Comment by achengli** [comment]
Hello,

I tried it in awesome and it did works fine, you should export luarocks path to get it working with luarocks packages.
```
luarocks path --lua-version=lua.5.? 
```
where *?*  means the version that are you using with awesome, commonly is lua 5.1.

You can add this line in your `.xinitrc`

```
eval $(luarocks path --lua-version=5.1)
```

**Comment by achengli** [comment]
It is even better to put it in the `.profile` than in the `.xinitrc` file.

**Comment by andOrlando** [comment]
Since this is a semi-widely used library I really don't want to make a breaking change like that. Can you get it to work without requiring someone to add to their .xinitrc?

**Comment by achengli** [comment]
Without including the path it doesn't work, Lua doesn't know where are the libraries located.

If this library is for personal use, then leave it as it is now so as  not to break it.

I did include the modifications for my personal purpose that was to convert some **HSL** color codes to **RGB** format in my  Neovim dotfiles.

Thanks!

**Comment by andOrlando** [comment]
What happens is in your awesomeWM config, you'll do a require("lib/color.lua") or something which calls init.lua which in turn sets the COLOR_DIR global variable, which is how lua knows where the files are. That's why it's in there in the first place, because without yeah lua wouldn't know where to put it.

Glad it works for you but I can't merge it as it stands because this library is primarily used by aWM users and it would break for them if I do this.

I'll look into alternative ways of making it work with luarocks at some point probably if I have time

**Comment by achengli** [comment]
> What happens is in your awesomeWM config, you'll do a require("lib/color.lua") or something which calls init.lua which in turn sets the COLOR_DIR global variable, which is how lua knows where the files are. That's why it's in there in the first place, because without yeah lua wouldn't know where to put it.
> 
> Glad it works for you but I can't merge it as it stands because this library is primarily used by aWM users and it would break for them if I do this.
> 
> I'll look into alternative ways of making it work with luarocks at some point probably if I have time

It's no problem, keep it as it is know
Thanks for the support!

**Pull request closed without merging**
